SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

DROP TABLE IF EXISTS `ezview_counterip`;
CREATE TABLE IF NOT EXISTS `ezview_counterip` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'The autoincrement ID',
  `node_id` int(11) NOT NULL COMMENT 'The node_id foreign relation',
  `remote_address` varchar(64) COLLATE utf8_unicode_ci NOT NULL COMMENT 'The remote ip relation',
  `count` int(11) NOT NULL DEFAULT '0' COMMENT 'The counter for a relation',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_node_id_remote` (`node_id`,`remote_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='EzViewCounter by IP' AUTO_INCREMENT=1 ;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
